apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/GoogleContainerTools/kpt-config-sync/releases/download/v1.19.0/config-sync-manifest.yaml
# optionally include admission-webhook.yaml to include admission-webhook
- https://github.com/GoogleContainerTools/kpt-config-sync/releases/download/v1.19.0/admission-webhook.yaml

patches:
# patch for cluster-name parameter
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --cluster-name=[*CLUSTER_NAME*]
  target:
    kind: Deployment
    name: reconciler-manager
    namespace: config-management-system
# patch for log level parameter
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --v=[*VERBOSITY*]
  target:
    kind: Deployment
    name: reconciler-manager
    namespace: config-management-system
# patch for metrics GSA annotation
- patch: |-
    - op: add
      path: "/metadata/annotations/iam.gke.io~1gcp-service-account"
      value: "[*GSA_EMAIL*]"
  target:
    kind: ServiceAccount
    name: default
    namespace: config-management-monitoring
# patch for private registry transform
# limitations:
# - kustomize cannot replace nested yaml in reconciler-manager-cm ConfigMap
# - kustomize requires enumerating every image name to replace registry
#
# The following replacements approach is suggested in https://github.com/kubernetes-sigs/kustomize/issues/4414#issuecomment-1018835598
# However, this doesn't work because it replaces the image name as well as the registry.
#replacements:
#- source:
#    kind: ConfigMap
#    name: local-config
#    fieldPath: data.registry
#  targets:
#  - select:
#      kind: Deployment
#    fieldPaths:
#    - spec.template.spec.containers.*.image
#    options:
#      delimiter: ":"
#      index: 0
#
# The following approach would work for top level images, but not those inside reconciler-manager-cm
#images:
#- name: gcr.io/config-management-release/reconciler
#  newName: us-docker.pkg.dev/sdowell-cs-dev/config-sync/reconciler
#- name: gcr.io/config-management-release/reconciler-manager
#  newName: us-docker.pkg.dev/sdowell-cs-dev/config-sync/reconciler-manager
#- name: gcr.io/config-management-release/admission-webhook
#  newName: us-docker.pkg.dev/sdowell-cs-dev/config-sync/admission-webhook
#- name: gcr.io/config-management-release/hydration-controller
#  newName: us-docker.pkg.dev/sdowell-cs-dev/config-sync/hydration-controller
#- name: gcr.io/config-management-release/oci-sync
#  newName: us-docker.pkg.dev/sdowell-cs-dev/config-sync/oci-sync
#- name: gcr.io/config-management-release/helm-sync
#  newName: us-docker.pkg.dev/sdowell-cs-dev/config-sync/helm-sync
#- name: gcr.io/config-management-release/gcenode-askpass-sidecar
#  newName: us-docker.pkg.dev/sdowell-cs-dev/config-sync/gcenode-askpass-sidecar
#- name: gcr.io/config-management-release/resource-group-controller
#  newName: us-docker.pkg.dev/sdowell-cs-dev/config-sync/resource-group-controller
#- name: gcr.io/config-management-release/git-sync
#  newName: us-docker.pkg.dev/sdowell-cs-dev/config-sync/git-sync
#- name: gcr.io/config-management-release/otelcontribcol
#  newName: us-docker.pkg.dev/sdowell-cs-dev/config-sync/otelcontribcol
